/** Constants and pure helpers shared by every verb. Mirrors the Python module's semantics exactly. */
import type { BodyItem, NodeRecord } from "./types.js"
import { sha1Json, sha256Json } from "./hash.js"
import { fingerprint, truthy } from "./state.js"
import { signature, splitComment } from "./pseudocode.js"
import { isAlnumChar, isAlphaChar, isDigit, isIdentifier, isLower, lstrip, partition, repr, rstrip, sorted, split, splitWs, strip } from "./pystr.js"

export const LEDGER = "ledger.json"
export const LOG = ".stepwise.log"
export const JOURNAL = ".stepwise-transaction.json"
export const LOCK = ".stepwise.lock"
export const CODE_COL = 58
export const CONTRACT_KEYS = ["pre", "post", "failure", "cancellation", "invariant", "progress"] as const
export const TEXT_FIELDS = ["gloss", "effect", "statement"] as const
export const LIST_FIELDS = ["walkthrough", "composition", "decisions", "deferred", "adaptation"] as const
export const JSON_SET_FIELDS = [...TEXT_FIELDS, "contract", ...LIST_FIELDS, "depends", "realization", "verification", "implementation_plan", "behavior"] as const
export const REALIZATION = ["not-started", "partial", "implemented"] as const
export const VERIFICATION = ["unverified", "partial", "verified", "stale", "failed"] as const
export const DESIGN = ["draft", "approved", "stale", "superseded", "retired"] as const
/** design state machine: "from->to" -> verb that makes the move. Nothing else moves a node. */
export const TRANSITIONS: Record<string, string> = {
  "draft->approved": "approve",
  "approved->draft": "reopen",
  "stale->draft": "reopen",
  "retired->draft": "reopen",
  "approved->stale": "stale",
  "draft->stale": "stale",
  "approved->superseded": "supersede",
  "stale->superseded": "supersede",
  "draft->superseded": "supersede",
  "approved->retired": "retire",
  "stale->retired": "retire",
  "draft->retired": "retire",
  "approved->approved": "approve",
}
export const transition = (from: string, to: string): string | undefined => TRANSITIONS[`${from}->${to}`]
export const legalMoves = (from: string): string[] => sorted(new Set(Object.entries(TRANSITIONS).filter(([k]) => k.startsWith(from + "->")).map(([, v]) => v)))
export const NEXT_STEP: Record<string, string> = {
  draft: "finish the draft (`set`, `answer`, `body`/`terminal`, `set walkthrough`/`composition`) then `approve`",
  approved: "nothing — refine its children, or `reopen` / `stale` / `supersede` / `retire` when something changes",
  "stale-intact": "`reaffirm --by WHO` after accepting changed dependencies, or `reopen` to revise the node",
  stale: "`reopen` and re-`approve` it, or `retire` / `supersede` it",
  superseded: "nothing — the replacement carries the work",
  retired: "nothing — the design dropped it; `reopen` only to revive it",
}
export const CONTROL = new Set(["if", "else", "elif", "loop", "while", "for", "until", "case", "match", "try", "finally", "repeat", "end", "upon", "atomic", "parallel"])
export const ENTRY_FILE: Record<string, string> = { term: "terms", fact: "facts", scenario: "scenarios" }
export const GENERATED = "_Generated by `stepwise.py` from ledger.json. Use the CLI; never edit this file._"

export const isNodeId = (s: string): boolean => s.length === 5 && s.startsWith("D-") && isDigit(s.slice(2))
export const isCtxId = (s: string): boolean => (s.startsWith("CTX-F") || s.startsWith("CTX-S")) && isDigit(s.slice(5))
export const isAdrId = (s: string): boolean => s.length === 8 && s.startsWith("ADR-") && isDigit(s.slice(4))
export const isIdent = (s: string): boolean => s.length > 0 && isIdentifier(s) && (isAlphaChar(s[0]) || s[0] === "_")

export const anchorOf = (heading: string): string => {
  let keep = ""
  for (const c of heading) keep += isAlnumChar(c) ? c.toLowerCase() : " -_".includes(c) ? " " : ""
  return splitWs(keep).join("-")
}

export const unknowns = (...texts: string[]): string[] => {
  const out = new Set<string>()
  for (const t of texts) {
    for (const w of splitWs(t)) {
      if (w.startsWith("?") && w.length > 1 && isAlphaChar(Array.from(w)[1])) out.add(rstrip(w.slice(1), ",.;:)]}"))
    }
  }
  return sorted(out)
}

export const fnOf = (statement: string): string => {
  const value = signature(statement)
  const [rawName, sep] = partition(value, "(")
  const name = strip(rawName)
  return sep && isIdent(name) ? name : ""
}

const NOT_CALLS = new Set([...CONTROL, "return", "assert", "invariant"])

export const callNames = (code: string): string[] => {
  const out: string[] = []
  const n = code.length
  let i = 0
  while (i < n) {
    const c = code[i]
    if (c === '"' || c === "'") {
      const quote = c
      i += 1
      while (i < n) {
        if (code[i] === "\\") {
          i += 2
          continue
        }
        if (code[i] === quote) {
          i += 1
          break
        }
        i += 1
      }
      continue
    }
    if (isAlphaChar(c) || c === "_") {
      let j = i
      while (j < n && (isAlnumChar(code[j]) || code[j] === "_")) j += 1
      let k = j
      while (k < n && code[k] === " ") k += 1
      const name = code.slice(i, j)
      const prev = i ? code[i - 1] : ""
      if (k < n && code[k] === "(" && prev !== "." && isIdent(name) && !NOT_CALLS.has(name.toLowerCase())) out.push(name)
      i = j
    } else i += 1
  }
  return out
}

export const stmtKind = (code: string): string => {
  const s = strip(code).toLowerCase()
  if (!s) return "comment"
  if (s.startsWith("{") || s.startsWith("assert ") || s.startsWith("invariant ")) return "assert"
  const head = rstrip(split(s, " ", 1)[0], ":")
  if (CONTROL.has(head) && (s.endsWith(":") || s.endsWith(" then") || s.endsWith(" do") || ["else", "repeat", "until", "end"].includes(head))) return "control"
  return "stmt"
}

/** '' when valid, else the reason. */
export const targetOk = (target: string): string => {
  const [head, sep, rest] = partition(target, ": ")
  const headOk = head.length > 0 && Array.from(head).every((c) => isAlnumChar(c) || c === "-" || c === "_") && isLower(head[0])
  if (!sep || !strip(rest) || !head || !headOk) {
    return `Target ${repr(target)} must read '<target>: <identifier>' (dbos: DBOS.startWorkflow, postgres: SELECT ... ORDER BY seq, ts: Promise.all)`
  }
  return ""
}

// ----------------------------------------------------------------------------- body text <-> items

export const indentOf = (line: string): number => line.length - lstrip(line).length
const count = (s: string, ch: string): number => s.split(ch).length - 1

export const joinContinuations = (raw: string[]): string[] => {
  const out: string[] = []
  let buf = ""
  let depth = 0
  for (const ln of raw) {
    if (depth <= 0 && out.length && strip(ln) && continues(out[out.length - 1], ln)) {
      out[out.length - 1] = merge(out[out.length - 1], ln)
      continue
    }
    buf = depth <= 0 ? ln : rstrip(buf) + (strip(ln).startsWith(")") || rstrip(buf).endsWith("(") ? "" : " ") + strip(ln)
    depth += count(ln, "(") - count(ln, ")")
    if (depth <= 0) {
      out.push(buf)
      buf = ""
      depth = 0
    }
  }
  if (buf) out.push(buf)
  return out
}

/** A deeper-indented line under an untagged, non-block statement wraps it (multi-line SQL, long expressions). */
export const continues = (prev: string, ln: string): boolean => {
  const [code, comment] = splitComment(prev)
  return Boolean(strip(code)) && !comment && stmtKind(code) === "stmt" && !rstrip(code).endsWith(":") && indentOf(ln) > indentOf(prev)
}

export const merge = (prev: string, ln: string): string => {
  const [code, sep, tag] = splitComment(ln)
  const joined = rstrip(prev) + " " + strip(code)
  return sep ? `${joined} --${tag}` : joined
}

export class BodyError extends Error {}

export const parseBody = (text: string, fn: string): BodyItem[] => {
  let raw = text.split(/\r\n|[\n\r\v\f\x1c\x1d\x1e\x85\u2028\u2029]/u).filter((ln) => strip(ln))
  if (raw.length) {
    const first = strip(raw[0])
    const prefix = split(first, " ", 1)[0].toLowerCase()
    if (prefix === "procedure" || prefix === "function") {
      if (fnOf(first) !== fn) throw new BodyError(`procedure signature must match ${fn}`)
      raw = raw.slice(1)
      if (raw.length && ["end procedure", "end function"].includes(strip(raw[raw.length - 1]).toLowerCase())) raw = raw.slice(0, -1)
    } else if (first.endsWith(":") && stmtKind(first) !== "control" && strip(partition(first, "(")[0]) === fn) raw = raw.slice(1)
  }
  for (const line of raw) {
    const head = strip(line).toLowerCase()
    if (["algorithm ", "require:", "ensure:", "input:", "output:"].some((p) => head.startsWith(p))) {
      throw new BodyError("algorithm captions and contract headers are generated; store requirements with set, and pass only the procedure body")
    }
    if (head.startsWith("procedure ") || head.startsWith("function ") || head === "end procedure" || head === "end function") {
      throw new BodyError("one procedure per node; represent helper procedures as child nodes")
    }
  }
  const lines = joinContinuations(raw)
  const base = lines.length ? Math.min(...lines.map((ln) => ln.length - lstrip(ln).length)) : 0
  const items: BodyItem[] = []
  for (const ln of lines) {
    const [code, sep, tag] = splitComment(strip(ln))
    const item: BodyItem = { indent: ln.length - lstrip(ln).length - base, code: strip(code) }
    if (sep) {
      let t = strip(tag)
      if (t.includes(" -- ")) {
        const [head, , gl] = partition(t, " -- ")
        t = strip(head)
        if (strip(gl)) item.gloss = strip(gl)
      }
      const words = splitWs(t)
      if (t.startsWith("↗") && words.length > 1) item.reuse = words[1]
      else if (t.startsWith("⇒") || t.startsWith("✓")) item.target = strip(t.slice(1))
      else if (words.length && isNodeId(rstrip(words[0], ":"))) {
        item.child = rstrip(words[0], ":")
        const rest = strip(lstrip(strip(t.slice(words[0].length)), ":"))
        if (rest) item.gloss = rest
      } else item.note = t
    }
    items.push(item)
  }
  return items
}

export const itemTag = (it: BodyItem): string => {
  if (it.child !== undefined) return it.gloss ? `${it.child}: ${it.gloss}` : it.child
  const gloss = it.gloss ? ` -- ${it.gloss}` : ""
  if (it.reuse !== undefined) return `↗ ${it.reuse}${gloss}`
  if (it.target !== undefined) return `⇒ ${it.target}${gloss}`
  return it.note ?? ""
}

export const fmt = (code: string, tag: string, indent: number): string => {
  const left = " ".repeat(indent) + code
  return tag ? `${left}${" ".repeat(Math.max(CODE_COL - left.length, 1))}-- ${tag}` : left
}

export const bodyText = (items: BodyItem[], indent = 2): string[] => items.map((it) => fmt(it.code, itemTag(it), indent + it.indent))

export const bodyHash = (items: BodyItem[]): string => sha1Json(items, { sortKeys: true }).slice(0, 12)

/** Bind approval to all current design content, including dependencies and plans. */
export const proposalHash = (n: NodeRecord): string => fingerprint(n)

export const legacyIntact = (n: NodeRecord): boolean => {
  const fields = ["statement", "gloss", "effect", "contract", "body", "walkthrough", "composition", "decisions", "deferred", "target", "adaptation"]
  const content: Record<string, unknown> = {}
  for (const f of fields) if (truthy(n[f])) content[f] = n[f]
  const digest = sha256Json(content, { sortKeys: true, ensureAscii: false }).slice(0, 16)
  return n.proposal_hash === digest && n.approved_hash === bodyHash(n.body ?? []) && n.contract_hash === contractHash(n)
}

export const intact = (n: NodeRecord): boolean =>
  Boolean(n.approved_content_hash) && n.approved_content_hash === fingerprint(n)
  && n.approved_hash === bodyHash(n.body ?? []) && n.contract_hash === contractHash(n)

export const commaValues = (values: string[]): string[] => {
  const out: string[] = []
  for (const value of values) for (const part of value.split(",")) {
    const p = strip(part)
    if (p && !out.includes(p)) out.push(p)
  }
  return out
}

/** What a caller depends on: the statement and the contract clauses. The body is the node's own business. */
export const contractHash = (n: NodeRecord): string => sha1Json([n.statement ?? "", n.target ?? "", n.contract ?? {}], { sortKeys: true }).slice(0, 12)

export const frontierStatement = (code: string): string => {
  const [lhs, sep, rhs] = partition(code, code.includes("←") ? "←" : "<-")
  if (sep) return `${strip(rhs)} -> ${strip(lhs)}`
  return code.startsWith("->") ? strip(code.slice(2)) : code.toLowerCase().startsWith("return ") ? strip(code.slice(7)) : code
}

export const nodeUnknowns = (n: NodeRecord): string[] => unknowns(n.gloss ?? "", n.effect ?? "", ...Object.values(n.contract ?? {}))

export const deepCopy = <T>(v: T): T => (v === undefined ? v : (JSON.parse(JSON.stringify(v)) as T))
