#!/usr/bin/env python3
"""Stepwise ledger CLI — owns every write to the design ledger. Agent-agnostic; call it from any agent.

Canonical data: <design-dir>/ledger.json (typed; this tool is the only writer).
Generated views (never edit; regenerated on every verb): DESIGN.md, CONTEXT.md, nodes/D-NNN.md.
ADRs stay markdown in docs/adr/ (repo convention); `adr new` stubs them, `adr accept` flips status.

Every verb ends with render + lint; exit 1 and `error <where>: <msg>` lines when something must be fixed.

  frontier  <dir>                                     what to pick next
  show      <dir> D-NNN                               node view to stdout
  new       <dir> D-NNN ["stmt"]                      draft node (frontier id, or the root with its statement)
  set       <dir> D-NNN gloss|effect "text"           one-line prose fields
  set       <dir> D-NNN pre|post|failure|invariant|<label> "clause"   contract clause, any lowercase label (<= 6 clauses; unknowns as ?slug)
  set       <dir> D-NNN walkthrough "l1" ["l2" "l3"]  <= 3 lines: what the function does (above the body)
  set       <dir> D-NNN composition|decisions|deferred|adaptation "b1" "b2" ...    bullet lists (replace)
  set       <dir> D-NNN depends "Name" ...            add dependencies that carry no ?slug (append; each must exist)
  set       <dir> D-NNN realization|verification <vocab>
  body      <dir> D-NNN [--file F]                    refinement body from stdin/file (pseudocode, `-- D-NNN: <one line>` / `-- ↗ D-NNN -- <one line>` / `-- ⇒ target -- <one line>`; every tagged line says what it does)
  answer    <dir> D-NNN slug "Name"                   ?slug -> name in every clause; name added to depends
  terminal  <dir> D-NNN "<target>: <identifier>"      leaf: the real thing (Exists test enforced)
  approve   <dir> D-NNN                               after the user says yes; refuses while anything is missing
  reopen    <dir> D-NNN "reason"                      approved -> draft for revision (history keeps the reason)
  stale     <dir> D-NNN "reason"                      dependency changed
  supersede <dir> D-OLD D-NEW "reason"
  evidence  <dir> D-NNN --kind K --ref R --result pass|fail [--note N]
  entry     <dir> term|fact|scenario "Heading" "definition" [--source S] [--avoid a,b] [--not T] [--example E]
                                                      [--given G --when W --then T --excludes X --settles T]
  change    <dir> <ref> [--definition D] [--rename "New Heading"] [--status confirmed|stale] --reason R   sharpen, rename or stale an entry
  meta      <dir> title|scope "text" | nongoals "a" "b" ...
  ambiguity <dir> "claim" "conflict" D-NNN | ambiguity <dir> "claim" --drop
  adr       <dir> new "Title" --constrains D-NNN[,D-MMM] | adr <dir> accept ADR-NNNN | adr <dir> supersede ADR-OLD ADR-NEW
                                                      adr <dir> constrains ADR-NNNN --constrains D-NNN[,D-MMM]   rewrite the constrained set
  sync      <dir>                                     render + lint (after hand-editing an ADR paragraph)
  check     <dir>                                     lint only, no writes

Stdlib only, no regex: the ledger is typed data, not text to be parsed.
"""
from __future__ import annotations

import argparse
import datetime as _dt
import hashlib
import json
import os
import sys
from pathlib import Path

LEDGER = "ledger.json"
LOG = ".stepwise.log"
CODE_COL = 58
CONTRACT_KEYS = ("pre", "post", "failure", "cancellation", "invariant", "progress")
TEXT_FIELDS = ("gloss", "effect")
LIST_FIELDS = ("walkthrough", "composition", "decisions", "deferred", "adaptation")
REALIZATION = ("not-started", "partial", "implemented")
VERIFICATION = ("unverified", "partial", "verified", "stale")
DESIGN = ("draft", "approved", "stale", "superseded")
CONTROL = {"if", "else", "elif", "loop", "while", "for", "until", "case", "match", "try", "finally"}
OWN_CODE = {"service", "module", "application", "application-service", "app", "own", "internal", "our", "runtime"}
ENTRY_FILE = {"term": "terms", "fact": "facts", "scenario": "scenarios"}
GENERATED = "_Generated by `stepwise.py` from ledger.json. Use the CLI; never edit this file._"


def today() -> str:
    return _dt.date.today().isoformat()


def now() -> str:
    return _dt.datetime.now().isoformat(timespec="microseconds")


def is_node_id(s: str) -> bool:
    return len(s) == 5 and s.startswith("D-") and s[2:].isdigit()


def is_ctx_id(s: str) -> bool:
    return s.startswith(("CTX-F", "CTX-S")) and s[5:].isdigit()


def is_adr_id(s: str) -> bool:
    return len(s) == 8 and s.startswith("ADR-") and s[4:].isdigit()


def is_ident(s: str) -> bool:
    return bool(s) and s.isidentifier() and (s[0].islower() or s[0] == "_")


def anchor_of(heading: str) -> str:
    keep = "".join(c.lower() if c.isalnum() else " " if c in " -_" else "" for c in heading)
    return "-".join(keep.split())


def unknowns(*texts: str) -> list[str]:
    out: set[str] = set()
    for t in texts:
        for w in t.split():
            if w.startswith("?") and len(w) > 1 and w[1].isalpha():
                out.add(w[1:].rstrip(",.;:)]}"))
    return sorted(out)


def fn_of(statement: str) -> str:
    s = statement.split("<-", 1)[1] if "<-" in statement else statement
    s = s.strip()
    if s.startswith("->"):
        s = s[2:].strip()
    name = s.partition("(")[0].strip()
    return name if is_ident(name) else ""


def call_names(code: str) -> list[str]:
    out, i, n = [], 0, len(code)
    while i < n:
        c = code[i]
        if c.isalpha() or c == "_":
            j = i
            while j < n and (code[j].isalnum() or code[j] == "_"):
                j += 1
            k = j
            while k < n and code[k] == " ":
                k += 1
            name, prev = code[i:j], code[i - 1] if i else ""
            if k < n and code[k] == "(" and prev != "." and is_ident(name) and name not in CONTROL:
                out.append(name)
            i = j
        else:
            i += 1
    return out


def stmt_kind(code: str) -> str:
    s = code.strip()
    if s.startswith("{"):
        return "assert"
    if s.endswith(":") and s.split(" ", 1)[0].rstrip(":") in CONTROL:
        return "control"
    return "stmt"


def target_ok(target: str) -> str:
    """'' when valid, else the reason."""
    head, sep, rest = target.partition(": ")
    first = head.replace("-", " ").split(" ")[0].lower() if head else ""
    if first in OWN_CODE:
        return f"Target {target!r} names design-owned code; a target must exist outside the design today (platform, language, repo fn on disk). Refine further, or collapse with `-- ⇒` lines"
    if not sep or not rest.strip() or not head or not all(c.isalnum() or c in "-_" for c in head) or not head[0].islower():
        return f"Target {target!r} must read '<target>: <identifier>' (dbos: DBOS.startWorkflow, postgres: SELECT ... ORDER BY seq, ts: Promise.all)"
    return ""


# ----------------------------------------------------------------------------- body text <-> items


def join_continuations(raw: list[str]) -> list[str]:
    out, buf, depth = [], "", 0
    for ln in raw:
        buf = ln if depth <= 0 else buf.rstrip() + ("" if ln.strip().startswith(")") or buf.rstrip().endswith("(") else " ") + ln.strip()
        depth += ln.count("(") - ln.count(")")
        if depth <= 0:
            out.append(buf)
            buf, depth = "", 0
    if buf:
        out.append(buf)
    return out


def parse_body(text: str, fn: str) -> list[dict]:
    lines = [ln for ln in join_continuations(text.splitlines()) if ln.strip()]
    if lines:
        first = lines[0].strip()
        if first.endswith(":") and stmt_kind(first) != "control" and first.partition("(")[0].strip() == fn:
            lines = lines[1:]
    base = min((len(ln) - len(ln.lstrip()) for ln in lines), default=0)
    items = []
    for ln in lines:
        code, sep, tag = ln.strip().partition("--")
        item: dict = {"indent": len(ln) - len(ln.lstrip()) - base, "code": code.strip()}
        if sep:
            t = tag.strip()
            if " -- " in t:  # `-- <tag> -- <one line saying what this line does>`
                t, _, gl = t.partition(" -- ")
                t = t.strip()
                if gl.strip():
                    item["gloss"] = gl.strip()
            words = t.split()
            if t.startswith("↗") and len(words) > 1:
                item["reuse"] = words[1]
            elif t[:1] in ("⇒", "✓"):
                item["target"] = t[1:].strip()
            elif words and is_node_id(words[0].rstrip(":")):
                item["child"] = words[0].rstrip(":")
                rest = t[len(words[0]):].strip().lstrip(":").strip()
                if rest:
                    item["gloss"] = rest  # `-- D-NNN: <one line>`
            else:
                item["note"] = t
        items.append(item)
    return items


def item_tag(it: dict) -> str:
    if "child" in it:
        return f"{it['child']}: {it['gloss']}" if it.get("gloss") else it["child"]
    gloss = f" -- {it['gloss']}" if it.get("gloss") else ""
    if "reuse" in it:
        return f"↗ {it['reuse']}{gloss}"
    if "target" in it:
        return f"⇒ {it['target']}{gloss}"
    return it.get("note", "")


def fmt(code: str, tag: str, indent: int) -> str:
    left = " " * indent + code
    return f"{left}{' ' * max(CODE_COL - len(left), 1)}-- {tag}" if tag else left


def body_text(items: list[dict], indent: int = 2) -> list[str]:
    return [fmt(it["code"], item_tag(it), indent + it["indent"]) for it in items]


def body_hash(items: list[dict]) -> str:
    return hashlib.sha1(json.dumps(items, sort_keys=True).encode()).hexdigest()[:12]


def frontier_statement(code: str) -> str:
    lhs, sep, rhs = code.partition("<-")
    if sep:
        return f"{rhs.strip()} -> {lhs.strip()}"
    return code[2:].strip() if code.startswith("->") else code


# ----------------------------------------------------------------------------- ledger


class Ledger:
    def __init__(self, d: Path):
        self.dir = d
        self.path = d / LEDGER
        self.data: dict = json.loads(self.path.read_text(encoding="utf-8")) if self.path.exists() else {}
        self.errors: list[str] = []
        self.warnings: list[str] = []

    # --- storage
    @classmethod
    def create(cls, d: Path, title: str) -> "Ledger":
        d.mkdir(parents=True, exist_ok=True)
        led = cls(d)
        led.data = {"schema": 1, "title": title, "scope": "", "nongoals": [], "ambiguities": [],
                    "nodes": {}, "terms": {}, "facts": {}, "scenarios": {}}
        led.save()
        return led

    def save(self) -> None:
        self.data["nodes"] = dict(sorted(self.nodes.items()))
        self.path.write_text(json.dumps(self.data, indent=1, ensure_ascii=False) + "\n", encoding="utf-8")

    @property
    def nodes(self) -> dict[str, dict]:
        return self.data.setdefault("nodes", {})

    def node(self, nid: str) -> dict | None:
        return self.nodes.get(nid)

    @property
    def title(self) -> str:
        return self.data.get("title") or self.dir.name.replace("-", " ").title()

    # --- derived structure
    def parents(self, nid: str) -> list[str]:
        return sorted(pid for pid, p in self.nodes.items() if any(it.get("child") == nid or it.get("reuse") == nid for it in p.get("body", [])))

    def roots(self) -> list[str]:
        return [nid for nid in self.nodes if not self.parents(nid)]

    def frontier(self) -> dict[str, tuple[str, str]]:
        out: dict[str, tuple[str, str]] = {}
        for pid, p in self.nodes.items():
            if p["design"] == "draft":
                continue
            for it in p.get("body", []):
                cid = it.get("child")
                if cid and cid not in self.nodes and cid not in out:
                    out[cid] = (frontier_statement(it["code"]), pid)
        return out

    def status(self, nid: str) -> str:
        n = self.nodes[nid]
        if n["design"] == "draft":
            if n.get("adr_pending"):
                return f"draft (ADR pending {n['adr_pending']})"
            k = len(node_unknowns(n))
            return f"draft ({k} ?)" if k else "draft"
        if n["design"] == "superseded":
            return f"superseded by {n.get('superseded_by', '?')}"
        return n["design"]

    def is_terminal(self, n: dict) -> bool:
        return bool(n.get("target")) and not n.get("body")

    def is_collapsed(self, n: dict) -> bool:
        stmts = [it for it in n.get("body", []) if stmt_kind(it["code"]) == "stmt"]
        return bool(stmts) and all("target" in it for it in stmts)

    def inline_parent(self, nid: str) -> str | None:
        ps = self.parents(nid)
        if len(ps) != 1:
            return None
        return ps[0] if any(it.get("child") == nid for it in self.nodes[ps[0]].get("body", [])) else None

    # --- context lookups
    def entry(self, ref: str) -> tuple[str, str, dict] | None:
        """(kind-file, key, entry) for a term name or CTX id."""
        r = ref.strip()
        if is_ctx_id(r):
            f = "facts" if r[4] == "F" else "scenarios"
            e = self.data.get(f, {}).get(r)
            return (f, r, e) if e else None
        for k, e in self.data.get("terms", {}).items():
            if k.lower() == r.lower():
                return ("terms", k, e)
        return None

    def adrs(self) -> list[dict]:
        return parse_adrs(self.adr_dir())

    def adr_dir(self) -> Path | None:
        return next((p / "adr" for p in [self.dir, *self.dir.parents][:5] if (p / "adr").is_dir()), None)

    def resolves(self, ref: str) -> bool:
        return (is_node_id(ref) and (ref in self.nodes or ref in self.frontier())) or \
            (is_adr_id(ref) and any(a["id"] == ref for a in self.adrs())) or self.entry(ref) is not None

    def canonical(self, ref: str) -> str:
        e = self.entry(ref)
        return e[1] if e else ref.strip()

    def used_by(self) -> dict[str, list[str]]:
        idx: dict[str, list[str]] = {}
        for nid, n in self.nodes.items():
            for r in n.get("depends", []):
                e = self.entry(r)
                if e:
                    idx.setdefault(e[1], []).append(nid)
        for sid, s in self.data.get("scenarios", {}).items():
            for t in self.terms_in(s.get("settles", "")):
                idx.setdefault(t, []).append(sid)
        return {k: sorted(set(v)) for k, v in idx.items()}

    def terms_in(self, text: str) -> list[str]:
        low = f" {text.lower()} "
        return [t for t in self.data.get("terms", {}) if f" {t.lower()} " in low or low.strip().startswith(t.lower())]


def node_unknowns(n: dict) -> list[str]:
    return unknowns(n.get("gloss", ""), n.get("effect", ""), *n.get("contract", {}).values())


# ----------------------------------------------------------------------------- ADR files (markdown, header only)


def set_header(lines: list[str], field: str, value: str) -> None:
    """Rewrite `field: …` in the ADR header block, adding the part if the line lacks it."""
    for i, ln in enumerate(lines[:8]):
        if ln.startswith("#") or ":" not in ln:
            continue
        parts = _header_parts(ln)
        if any(x.startswith(f"{field}:") for x in parts):
            lines[i] = " · ".join(f"{field}: {value}" if x.startswith(f"{field}:") else x for x in parts)
            return
    for i, ln in enumerate(lines[:8]):
        if ln.startswith("Kind:"):
            lines.insert(i + 1, f"{field}: {value}")
            return


def _header_parts(line: str) -> list[str]:
    return [p.strip() for p in line.replace(" | ", " · ").split(" · ")]


def parse_adrs(adr_dir: Path | None) -> list[dict]:
    out = []
    for p in sorted(adr_dir.glob("*.md")) if adr_dir else []:
        lines = p.read_text(encoding="utf-8").splitlines()
        aid, title = p.stem[:4], p.stem
        header: dict[str, str] = {}
        for ln in lines:
            if ln.startswith("# "):
                head = ln[2:].replace(" - ", " — ").replace(" – ", " — ")
                a, sep, t = head.partition(" — ")
                aid, title = (a.strip(), t.strip()) if sep else (head.strip(), head.strip())
            elif ln.startswith("## "):
                break
            else:
                for part in _header_parts(ln):
                    k, sep, v = part.partition(":")
                    if sep and k and k[0].isupper() and " " not in k.strip():
                        header[k.strip()] = v.strip()
        if not is_adr_id(aid):
            aid = f"ADR-{p.stem[:4]}" if p.stem[:4].isdigit() else p.stem
        constrains = [w.strip("[],") for w in header.get("Constrains", "").replace("(", " (").split() if is_node_id(w.strip("[],"))]
        out.append({"id": aid, "title": title, "status": header.get("Status", "?"), "constrains": constrains, "path": p, "lines": lines})
    return out


# ----------------------------------------------------------------------------- rendering


def rel(frm: Path, to: Path) -> str:
    return os.path.relpath(to, frm.parent)


def link_ref(led: Ledger, ref: str, frm: Path) -> str:
    if is_node_id(ref) and ref in led.nodes:
        return f"[{ref}]({rel(frm, led.dir / 'nodes' / f'{ref}.md')})"
    if is_adr_id(ref):
        a = next((a for a in led.adrs() if a["id"] == ref), None)
        return f"[{ref}]({rel(frm, a['path'])})" if a else ref
    e = led.entry(ref)
    if e:
        return f"[{e[1]}]({rel(frm, led.dir / 'CONTEXT.md')}#{anchor_of(e[1] if e[0] == 'terms' else e[1] + ' ' + e[2].get('name', ''))})"
    return ref


def render_node(led: Ledger, nid: str) -> str:
    n = led.nodes[nid]
    p = led.dir / "nodes" / f"{nid}.md"
    L = [f"# {nid} — {fn_of(n['statement']) or nid}", "", GENERATED, "",
         f"Kind: node · Index: [../DESIGN.md](../DESIGN.md)",
         f"Design: {led.status(nid)} · Realization: {n['realization']} · Verification: {n['verification']}",
         f"Parents: {', '.join(link_ref(led, x, p) for x in led.parents(nid)) or '-'}",
         f"Depends on: {', '.join(link_ref(led, x, p) for x in n.get('depends', [])) or '-'}",
         f"Approved: {n.get('approved') or '-'}", "",
         "## Statement", "", f"`{n['statement']}`" + (f" — {n['gloss']}" if n.get("gloss") else ""), "",
         "## Effect", "", n.get("effect") or "-", "",
         "## Contract", ""]
    L += [f"- {k.title()}: {v}" for k, v in n.get("contract", {}).items()] or ["-"]
    if n.get("body"):
        sig = n["statement"].split("<-", 1)[-1].strip().removeprefix("->").strip()
        L += ["", "## Refinement", ""]
        if n.get("walkthrough"):
            L += ["What it does:", *[f"{ln}" for ln in n["walkthrough"]], ""]
        L += ["```pseudo", sig + ":", *body_text(n["body"]), "```"]
        lines = [(it.get("child") or it.get("reuse") or it.get("target", ""),
                  it.get("gloss") or led.nodes.get(it.get("child") or it.get("reuse", ""), {}).get("gloss", ""))
                 for it in n["body"] if any(k in it for k in ("child", "reuse", "target"))]
        if any(g for _, g in lines):
            L += ["", *[f"- {c} — {g}" for c, g in lines if g]]
    children = {it.get("child") for it in n.get("body", []) if it.get("child")}
    deferred = [*n.get("deferred", []), *[f"{a['claim']} — {a['conflict']} → {a['resolves_at']}" for a in led.data.get("ambiguities", []) if a["resolves_at"] in children]]
    for f, title, items in (("composition", "Composition argument", n.get("composition", [])), ("decisions", "Decisions", n.get("decisions", [])), ("deferred", "Deferred", deferred)):
        if items:
            L += ["", f"## {title}", "", *[f"- {b}" for b in items]]
    if s := n.get("superseded"):
        L += ["", f"## Superseded refinement", "", f"Replaced {s['date']}" + (f" — {s['reason']}" if s.get("reason") else "")]
        if s.get("body"):
            L += ["", "```pseudo", *body_text(s["body"]), "```"]
        for f, title in (("composition", "Composition argument"), ("decisions", "Decisions"), ("deferred", "Deferred")):
            if s.get(f):
                L += ["", f"Superseded {title.lower()}:", *[f"- {b}" for b in s[f]]]
    collapsed = not n.get("target") and led.is_collapsed(n)
    if n.get("target") or n.get("adaptation") or collapsed:
        L += ["", "## Realization", ""]
        if n.get("target"):
            L.append(f"Target: `{n['target']}`")
        elif collapsed:
            heads = dict.fromkeys(it["target"].split(":", 1)[0].strip() for it in n["body"] if it.get("target"))
            L.append("Collapsed leaf. Targets: " + ", ".join(f"`{h}`" for h in heads))
        L += [f"Adaptation: {a}" for a in n.get("adaptation", [])]
    if n.get("evidence"):
        L += ["", "## Evidence", ""]
        for i, ev in enumerate(n["evidence"], 1):
            L += [f"### EV-{i} {ev['kind']} — {ev['result']}", f"{ev['date']} · {ev['ref']}" + (f" · {ev['note']}" if ev.get("note") else "")]
    if n.get("history"):
        L += ["", "## History", "", *[f"- {h['date']} — {h['event']}" + (f": {h['reason']}" if h.get("reason") else "") for h in n["history"]]]
    return "\n".join(L) + "\n"


def tag_for(led: Ledger, cid: str, reuse: bool) -> str:
    n = led.nodes.get(cid)
    if n and n["design"] == "approved" and led.is_terminal(n):
        return f"{cid} {'✓' if n['verification'] == 'verified' else '⇒'} {n['target']}"
    if reuse or (n and len(led.parents(cid)) >= 2):
        return f"↗ {cid}"
    if not n:
        return f"{cid} (frontier)"
    if n["design"] == "draft":
        return f"{cid} ({led.status(cid)})"
    if n["design"] in ("stale", "superseded"):
        return f"{cid} ({led.status(cid)})"
    if led.is_terminal(n):
        return f"{cid} {'✓' if n['verification'] == 'verified' else '⇒'} {n['target']}"
    return cid


def emit(led: Ledger, nid: str, indent: int, out: list[str], emitted: set[str]) -> None:
    emitted.add(nid)
    for it in led.nodes[nid].get("body", []):
        here = indent + it["indent"]
        if "child" in it or "reuse" in it:
            cid, reuse = it.get("child") or it["reuse"], "reuse" in it
            out.append(fmt(it["code"], tag_for(led, cid, reuse), here))
            c = led.nodes.get(cid)
            if c and c["design"] == "approved" and c.get("body") and not reuse and led.inline_parent(cid) == nid and cid not in emitted:
                emit(led, cid, here + 2, out, emitted)
        else:
            out.append(fmt(it["code"], item_tag(it), here))


def render_program(led: Ledger) -> tuple[list[str], list[str]]:
    main: list[str] = []
    emitted: set[str] = set()
    for rid in led.roots():
        r = led.nodes[rid]
        main.append(fmt(r["statement"].split("<-", 1)[-1].strip().removeprefix("->").strip() + ":", tag_for(led, rid, False), 0))
        if r.get("body") and r["design"] != "draft":
            emit(led, rid, 2, main, emitted)
    procs: list[str] = []
    for nid, n in led.nodes.items():
        if nid in emitted or not n.get("body") or n["design"] == "draft" or not led.parents(nid) or led.inline_parent(nid):
            continue
        if procs:
            procs.append("")
        st = tag_for(led, nid, False).replace(nid, "").strip()
        sig = n["statement"].split("<-", 1)[-1].strip().removeprefix("->").strip() + ":"
        procs.append(fmt(sig, f"{nid}{' ' + st if st and not st.startswith('↗') else ''} (used by {', '.join(led.parents(nid))})", 0))
        emit(led, nid, 2, procs, emitted)
    return main, procs


def render_design(led: Ledger) -> str:
    d = led.dir
    fr = led.frontier()
    frontier = sorted(set(fr) | {nid for nid, n in led.nodes.items() if n["design"] == "draft"})
    L = [f"# {led.title} — Design", "", GENERATED, "", "Kind: index · Context: [./CONTEXT.md](./CONTEXT.md)",
         f"Root: {', '.join(led.roots()) or '-'} · Active frontier: {', '.join(frontier) or '-'}", "", "## Applicable ADRs", ""]
    L += [f"- [{a['id']} {a['title']}]({rel(d / 'DESIGN.md', a['path'])}) — {a['status']} — constrains {', '.join(a['constrains']) or '-'}" for a in led.adrs()] or ["- none"]
    L += ["", "## Nodes", "", "| ID | Statement | Parents | Design | Realization | Verification | File |", "| --- | --- | --- | --- | --- | --- | --- |"]
    rows = [(nid, n["statement"].replace("|", "\\|"), ", ".join(led.parents(nid)) or "-", led.status(nid), n["realization"], n["verification"], f"[nodes/{nid}.md](nodes/{nid}.md)") for nid, n in led.nodes.items()]
    rows += [(fid, s.replace("|", "\\|"), p, "frontier", "not-started", "unverified", "-") for fid, (s, p) in fr.items()]
    L += ["| " + " | ".join(r) + " |" for r in sorted(rows)]
    main, procs = render_program(led)
    L += ["", "## Program", "", "```pseudo", *main, "```"]
    if procs:
        L += ["", "### Procedures", "", "```pseudo", *procs, "```"]
    return "\n".join(L) + "\n"


def render_context(led: Ledger) -> str:
    D = led.data
    used = led.used_by()
    L = [f"# {led.title} — Shared Context", "", GENERATED, "", f"Kind: index · Status: active · Design: [./DESIGN.md](./DESIGN.md)", "",
         "## Scope", "", D.get("scope") or "-", "", "## Vocabulary", "", "| Term | Is | Avoid | Used by |", "| --- | --- | --- | --- |"]
    for k, e in sorted(D.get("terms", {}).items(), key=lambda kv: kv[0].lower()):
        L.append(f"| [{k}](#{anchor_of(k)}) | {e['definition'].split('. ')[0].rstrip('.')} | {', '.join(e.get('avoid', [])) or '-'} | {', '.join(used.get(k, [])) or '-'} |")
    L += ["", "## Facts and constraints", "", "| ID | Fact | Status | Used by |", "| --- | --- | --- | --- |"]
    for k, e in sorted(D.get("facts", {}).items()):
        L.append(f"| [{k}](#{anchor_of(k + ' ' + e['name'])}) | {e['definition'].split('. ')[0].rstrip('.')} | {e.get('status', 'confirmed')} | {', '.join(used.get(k, [])) or '-'} |")
    L += ["", "## Scenarios", "", "| ID | Scenario | Settles |", "| --- | --- | --- |"]
    for k, e in sorted(D.get("scenarios", {}).items()):
        L.append(f"| [{k}](#{anchor_of(k + ' ' + e['name'])}) | {e['name']} | {e.get('settles') or '-'} |")
    L += ["", "## Open ambiguities", "", "| Term / claim | Conflict | Resolves at |", "| --- | --- | --- |"]
    L += [f"| {a['claim']} | {a['conflict']} | {a['resolves_at']} |" for a in D.get("ambiguities", [])]
    L += ["", "## Explicit non-goals", "", *([f"- {g}" for g in D.get("nongoals", [])] or ["- none"])]
    L += ["", "## Terms", ""]
    for k, e in sorted(D.get("terms", {}).items(), key=lambda kv: kv[0].lower()):
        L += [f"### {k}", "", f"Confirmed: {e['confirmed']}" + (f" · Source: {e['source']}" if e.get("source") else ""), "", e["definition"]]
        for lab, key in (("Avoid", "avoid"), ("Not", "not")):
            if e.get(key):
                L.append(f"{lab}: {', '.join(e[key])}")
        if e.get("example"):
            L.append(f"Example: {e['example']}")
        L += [f"Used by: {', '.join(used.get(k, [])) or '-'}", *_changed(e), ""]
    L += ["## Facts", ""]
    for k, e in sorted(D.get("facts", {}).items()):
        L += [f"### {k} {e['name']}", "", f"Status: {e.get('status', 'confirmed')} · Confirmed: {e['confirmed']}" + (f" · Source: {e['source']}" if e.get("source") else ""), "",
              e["definition"], f"Used by: {', '.join(used.get(k, [])) or '-'}", *_changed(e), ""]
    L += ["## Scenario entries", ""]
    for k, e in sorted(D.get("scenarios", {}).items()):
        L += [f"### {k} {e['name']}", "", f"Confirmed: {e['confirmed']}" + (f" · Settles: {e['settles']}" if e.get("settles") else ""), ""]
        L += [f"{w.title()} {e[w]}" for w in ("given", "when", "then") if e.get(w)]
        if e.get("excludes"):
            L.append(f"Excludes: {e['excludes']}")
        L += _changed(e) + [""]
    return "\n".join(L).rstrip("\n") + "\n"


def _changed(e: dict) -> list[str]:
    return [f"Changed: {c['at'][:10]} — {c['reason']}" for c in e.get("changed", [])]


def render_all(led: Ledger) -> dict[Path, str]:
    out = {led.dir / "DESIGN.md": render_design(led), led.dir / "CONTEXT.md": render_context(led)}
    for nid in led.nodes:
        out[led.dir / "nodes" / f"{nid}.md"] = render_node(led, nid)
    return out


def write_views(led: Ledger) -> None:
    (led.dir / "nodes").mkdir(parents=True, exist_ok=True)
    for p, text in render_all(led).items():
        if not p.exists() or p.read_text(encoding="utf-8") != text:
            p.write_text(text, encoding="utf-8")


# ----------------------------------------------------------------------------- lint


def check(led: Ledger) -> None:
    E = led.errors.append
    W = led.warnings.append
    nodes = led.nodes
    fr = led.frontier()
    if nodes and len(led.roots()) != 1:
        E(f"ledger: expected exactly one root node; found {led.roots()}")
    adrs = led.adrs()
    adr_ids = {a["id"] for a in adrs}
    for nid, n in nodes.items():
        where = f"{nid}"
        if n["design"] not in DESIGN:
            E(f"{where}: design {n['design']!r} not in {DESIGN}")
        if n["realization"] not in REALIZATION:
            E(f"{where}: realization {n['realization']!r} not in {REALIZATION}")
        if n["verification"] not in VERIFICATION:
            E(f"{where}: verification {n['verification']!r} not in {VERIFICATION}")
        if n["design"] == "superseded" and n.get("superseded_by") not in nodes and n.get("superseded_by") not in fr:
            E(f"{where}: superseded_by {n.get('superseded_by')!r} does not exist")
        if not fn_of(n["statement"]):
            E(f"{where}: statement {n['statement']!r} has no call `f(...)`")
        if len(n.get("contract", {})) > 6:
            E(f"{where}: contract has {len(n['contract'])} clauses > 6")
        body = n.get("body", [])
        stmts = [it for it in body if stmt_kind(it["code"]) == "stmt"]
        if len(stmts) > 12:
            E(f"{where}: refinement has {len(stmts)} statements > 12")
        for it in stmts:
            if not any(k in it for k in ("child", "reuse", "target")) and call_names(it["code"]):
                E(f"{where}: untagged call {it['code']!r}; tag `-- D-NNN` (new id), `-- ↗ D-NNN` (reuse) or `-- ⇒ <target>: <identifier>`")
            if "reuse" in it and (it["reuse"] not in nodes or nodes[it["reuse"]]["design"] != "approved"):
                E(f"{where}: reuse ↗ {it['reuse']} but it is not an approved node")
            if "target" in it and (why := target_ok(it["target"])):
                E(f"{where}: {why}")
        if n["design"] == "approved":
            if node_unknowns(n):
                E(f"{where}: approved with unresolved ?{', ?'.join(node_unknowns(n))}")
            if not body and not n.get("target"):
                E(f"{where}: approved needs a refinement body (`body`) or a target (`terminal`)")
            if body and not led.is_collapsed(n) and not n.get("composition"):
                E(f"{where}: approved composite lacks composition (`set {nid} composition ...`)")
            if n.get("approved_hash") and n["approved_hash"] != body_hash(body):
                E(f"{where}: body changed since approval; `reopen` then `approve` again")
            if n.get("adr_pending"):
                E(f"{where}: approved while {n['adr_pending']} is pending; `adr accept` first")
        for ad in n.get("adaptation", []):
            if "→" not in ad and "->" not in ad:
                E(f"{where}: adaptation {ad!r} must read '<clause> → <concrete construct>' (query text, API call + args, type); behaviour prose is not adaptation")
        if n.get("target"):
            if (why := target_ok(n["target"])):
                E(f"{where}: {why}")
            if body and not led.is_collapsed(n):
                E(f"{where}: has target and child statements; a terminal has no body, a collapsed leaf tags every statement `-- ⇒`")
        for r in n.get("depends", []):
            if is_node_id(r) or is_adr_id(r):
                if not led.resolves(r):
                    E(f"{where}: depends on {r} which does not exist")
                continue
            e = led.entry(r)
            if not e:
                E(f"{where}: depends on {r!r}: no term / fact / scenario with that name or id (`entry` first)")
            elif n["design"] == "approved" and n.get("approved_at"):
                last = max((c["at"] for c in e[2].get("changed", [])), default="")
                if last > n["approved_at"]:
                    E(f"{where}: {e[1]} changed {last[:10]} after approval {n['approved_at'][:10]}; `stale` or `reopen`+`approve`")
        if n.get("adr_pending") and n["adr_pending"] not in adr_ids:
            E(f"{where}: adr_pending {n['adr_pending']} has no file")
    for a in adrs:
        if len(a["lines"]) > 40:
            E(f"{a['path'].name}: {len(a['lines'])} lines > 40")
        for rid in a["constrains"]:
            if rid in nodes and nodes[rid]["design"] in ("stale", "superseded"):
                E(f"{a['path'].name}: constrains {rid} which is {led.status(rid)}; re-point to the live node")
            elif rid not in nodes and rid not in fr:
                E(f"{a['path'].name}: constrains {rid} which does not exist")
        if "<1–3 sentences" in "\n".join(a["lines"]):
            W(f"{a['path'].name}: paragraph still a placeholder")
    for amb in led.data.get("ambiguities", []):
        r = amb["resolves_at"]
        if r in nodes and nodes[r]["design"] == "approved":
            E(f"ambiguity {amb['claim']!r} resolves at {r} which is approved; re-point (`ambiguity`) or drop it")
    for f in ("terms", "facts", "scenarios"):
        for k, e in led.data.get(f, {}).items():
            if not (e.get("definition") or e.get("then")):
                E(f"{f}/{k}: empty definition")
            if f == "scenarios" and e.get("settles") and not led.terms_in(e["settles"]):
                W(f"{f}/{k}: settles {e['settles']!r} names no term")
            for t in e.get("not", []):
                if not led.entry(t):
                    W(f"{f}/{k}: not {t!r} is not a term")
    for p, text in render_all(led).items():
        if not p.exists():
            E(f"{p.name}: missing; run sync")
        elif p.read_text(encoding="utf-8") != text:
            E(f"{os.path.relpath(p, led.dir)}: generated view edited or stale; run sync (edit the ledger via the CLI, never the view)")


def report(led: Ledger, head: str = "") -> int:
    if head:
        print(head)
    for w in led.warnings:
        print(f"warn  {w}")
    for e in led.errors:
        print(f"error {e}")
    print(f"{'FAIL' if led.errors else 'ok'}  {led.dir.name}: {len(led.nodes)} nodes, {len(led.frontier())} frontier, {len(led.errors)} errors, {len(led.warnings)} warnings")
    return 1 if led.errors else 0


def derive_depends(led: Ledger) -> None:
    """A term / CTX id / ADR id named in a node's prose is a dependency; record it so `Used by` and staleness follow."""
    adrs = led.adrs()
    adr_ids = {a["id"] for a in adrs}
    for adr in adrs:
        for nid in adr["constrains"]:
            n = led.nodes.get(nid)
            if n is not None and adr["id"] not in n.setdefault("depends", []):
                n["depends"].append(adr["id"])
    for n in led.nodes.values():
        text = " ".join([n.get("gloss", ""), n.get("effect", ""), *n.get("contract", {}).values()])
        deps = n.setdefault("depends", [])
        for word in text.split():
            w = word.strip(",.;:()[]`")
            if (is_ctx_id(w) and led.entry(w)) or (is_adr_id(w) and w in adr_ids):
                if w not in deps:
                    deps.append(w)
        padded = f" {text} "
        for t in led.data.get("terms", {}):
            if f" {t} " in padded.replace(",", " ").replace(".", " ").replace(";", " ").replace("(", " ").replace(")", " ") and t not in deps:
                deps.append(t)


def finish(led: Ledger, head: str = "") -> int:
    derive_depends(led)
    led.save()
    write_views(led)
    check(led)
    return report(led, head)


def fail(msg: str) -> int:
    print(f"error {msg}", file=sys.stderr)
    return 1


# ----------------------------------------------------------------------------- verbs


def need(led: Ledger, nid: str) -> dict | None:
    n = led.node(nid)
    if n is None:
        fail(f"{nid}: no such node" + (" — it is on the frontier; `new` it first" if nid in led.frontier() else ""))
    return n


def hist(n: dict, event: str, reason: str = "") -> None:
    n.setdefault("history", []).append({"date": today(), "event": event, **({"reason": reason} if reason else {})})


def v_frontier(led: Ledger, a) -> int:
    for fid, (stmt, parent) in sorted(led.frontier().items()):
        print(f"{fid}  frontier  {stmt}  (child of {parent})")
    drafts = [nid for nid, n in led.nodes.items() if n["design"] == "draft"]
    for nid in drafts:
        print(f"{nid}  {led.status(nid)}  {led.nodes[nid]['statement']}")
    if not led.frontier() and not drafts:
        print("frontier empty — every leaf terminal or collapsed" if led.nodes else 'no nodes — `new <dir> D-000 "outcome <- f(x)"`')
    return 0


def v_show(led: Ledger, a) -> int:
    if need(led, a.id) is None:
        return 1
    print(render_node(led, a.id), end="")
    return 0


def v_new(led: Ledger, a) -> int:
    if a.id in led.nodes:
        return fail(f"{a.id} already exists")
    fr = led.frontier()
    if a.id in fr:
        pid = fr[a.id][1]
        code = next(it["code"] for it in led.nodes[pid]["body"] if it.get("child") == a.id)
    elif a.statement and not led.nodes:
        code = a.statement
    elif a.statement:
        return fail(f"{a.id} is not on the frontier and a root already exists ({led.roots()}); pick from `frontier`")
    else:
        return fail(f"{a.id} is not on the frontier; a root needs its statement: new <dir> {a.id} \"outcome <- f(x)\"")
    if not fn_of(code):
        return fail(f"statement {code!r} has no call `f(...)`")
    led.nodes[a.id] = {"statement": code, "gloss": "", "effect": "", "contract": {}, "depends": [],
                       "design": "draft", "realization": "not-started", "verification": "unverified", "approved": ""}
    return finish(led, f"created {a.id} `{code}` (draft). Next: `set {a.id} gloss|effect|pre|post|failure|invariant ...` (unknowns as ?slug), then `answer`, `body`, `approve`.")


def v_set(led: Ledger, a) -> int:
    n = need(led, a.id)
    if n is None:
        return 1
    f, vals = a.field, a.value
    if f in TEXT_FIELDS:
        n[f] = " ".join(vals).strip()
    elif f in CONTRACT_KEYS or (f.isalpha() and f.islower() and f not in LIST_FIELDS + ("realization", "verification", "depends")):
        # any lowercase word is a contract clause label: pre, post, failure, invariant, budget, determinism, boundary, ...
        n.setdefault("contract", {})[f] = " ".join(vals).strip()
        if len(n["contract"]) > 6:
            return fail(f"{a.id}: contract would have {len(n['contract'])} clauses > 6")
    elif f in LIST_FIELDS:
        n[f] = [v.strip() for v in vals if v.strip()]
        if f == "walkthrough" and len(n[f]) > 3:
            return fail(f"{a.id}: walkthrough is {len(n[f])} lines > 3 — say what the function does, not how")
    elif f == "depends":
        deps = n.setdefault("depends", [])
        for v in vals:
            ref = led.canonical(v)
            if not led.resolves(ref):
                return fail(f"{v!r} is not a term / fact / scenario / node / ADR on disk — `entry` first")
            if ref not in deps:
                deps.append(ref)
        return finish(led, f"{a.id}.depends = {deps}")
    elif f == "realization":
        if vals[0] not in REALIZATION:
            return fail(f"realization must be one of {REALIZATION}")
        n[f] = vals[0]
    elif f == "verification":
        if vals[0] not in VERIFICATION:
            return fail(f"verification must be one of {VERIFICATION}")
        n[f] = vals[0]
    else:
        return fail(f"unknown field {f!r}; fields: {TEXT_FIELDS + CONTRACT_KEYS + LIST_FIELDS + ('realization', 'verification')}")
    if n["design"] == "approved" and f in TEXT_FIELDS + CONTRACT_KEYS:
        n["design"] = "draft"
        hist(n, "reopened", f"{f} edited after approval")
    return finish(led, f"{a.id}.{f} set" + (f"; open ?: {node_unknowns(n)}" if node_unknowns(n) else ""))


def v_body(led: Ledger, a) -> int:
    n = need(led, a.id)
    if n is None:
        return 1
    if n["design"] == "approved":
        return fail(f"{a.id} is approved; `reopen {a.id} \"reason\"` first")
    text = Path(a.file).read_text(encoding="utf-8") if a.file else sys.stdin.read()
    items = parse_body(text, fn_of(n["statement"]))
    if not items:
        return fail("empty body")
    n["body"] = items
    autotag(led, a.id)
    new = [it["child"] for it in n["body"] if it.get("child") and it["child"] not in led.nodes]
    return finish(led, f"{a.id} body: {len(items)} lines; children {sorted(set(new)) or 'none new'}")


def autotag(led: Ledger, nid: str) -> None:
    by_fn: dict[str, list[str]] = {}
    for oid, o in led.nodes.items():
        if oid != nid and fn_of(o["statement"]):
            by_fn.setdefault(fn_of(o["statement"]), []).append(oid)
    for it in led.nodes[nid].get("body", []):
        if stmt_kind(it["code"]) != "stmt" or any(k in it for k in ("child", "reuse", "target")):
            continue
        calls = call_names(it["code"])
        if len(calls) == 1 and len(by_fn.get(calls[0], [])) == 1:
            it["child"] = by_fn[calls[0]][0]


def v_answer(led: Ledger, a) -> int:
    n = need(led, a.id)
    if n is None:
        return 1
    slug = a.slug.lstrip("?")
    if slug not in node_unknowns(n):
        return fail(f"{a.id} has no ?{slug}; open: {node_unknowns(n) or 'none'}")
    ref = led.canonical(a.name)
    if not led.resolves(ref):
        return fail(f"{a.name!r} is not on disk — `entry <dir> term|fact|scenario \"{a.name}\" \"<definition>\"` first")

    def sub(t: str) -> str:
        words = t.split(" ")
        return " ".join(ref + w[len(slug) + 1:] if w.startswith("?" + slug) and w[len(slug) + 1:len(slug) + 2] in ("", ",", ".", ";", ":", ")", "]") else w for w in words)
    for f in TEXT_FIELDS:
        n[f] = sub(n.get(f, ""))
    n["contract"] = {k: sub(v) for k, v in n.get("contract", {}).items()}
    if ref not in n.setdefault("depends", []):
        n["depends"].append(ref)
    left = node_unknowns(n)
    return finish(led, f"{a.id}: ?{slug} -> {ref}; depends += {ref}" + (f"; open: {left}" if left else "; no ? left — propose the refinement"))


def v_terminal(led: Ledger, a) -> int:
    n = need(led, a.id)
    if n is None:
        return 1
    t = a.target.strip().strip("`")
    if (why := target_ok(t)):
        return fail(why)
    if n.get("body") and not led.is_collapsed(n):
        return fail(f"{a.id} has child statements; a terminal has no body (drop it) — or collapse: tag every statement `-- ⇒ <target>: <identifier>`")
    n["target"] = t
    return finish(led, f"{a.id} terminal ⇒ {t}. Add `set {a.id} adaptation \"<pseudo> → <real>\" ...` when shape changes, then `approve {a.id}`")


def v_approve(led: Ledger, a) -> int:
    n = need(led, a.id)
    if n is None:
        return 1
    problems = []
    if node_unknowns(n):
        problems.append(f"unresolved ?{', ?'.join(node_unknowns(n))} — `answer` each")
    for f in ("gloss", "effect"):
        if not n.get(f):
            problems.append(f"{f} empty — `set {a.id} {f} ...`")
    if not n.get("contract"):
        problems.append(f"contract empty — `set {a.id} pre|post|failure|invariant ...`")
    body = n.get("body", [])
    if not body and not n.get("target"):
        problems.append("no refinement body and no target — `body` (composite) or `terminal` (leaf)")
    if body and not n.get("walkthrough"):
        problems.append(f"walkthrough missing — `set {a.id} walkthrough \"...\"` (<= 3 lines: what the function does)")
    if body and not led.is_collapsed(n) and not n.get("composition"):
        problems.append(f"composition missing — `set {a.id} composition ...`")
    for it in body:
        tagged = next((k for k in ("child", "reuse", "target") if k in it), "")
        known = led.nodes.get(it.get("child") or it.get("reuse", ""), {}).get("gloss")
        if tagged and not it.get("gloss") and not known:
            how = f"-- {it['child']}: <one line>" if tagged == "child" else f"-- {item_tag(it)} -- <one line>"
            problems.append(f"{it['code']!r} says nothing about what it does — tag it `{how}`")
    for it in body:
        if stmt_kind(it["code"]) == "stmt" and not any(k in it for k in ("child", "reuse", "target")) and call_names(it["code"]):
            problems.append(f"untagged call {it['code']!r}")
    if n.get("target") and (why := target_ok(n["target"])):
        problems.append(why)
    if n.get("adr_pending"):
        problems.append(f"{n['adr_pending']} pending — `adr accept {n['adr_pending']}` after the user accepts it")
    if problems:
        print(f"refused {a.id}:", file=sys.stderr)
        for p in problems:
            print(f"  - {p}", file=sys.stderr)
        return 1
    re_approval = bool(n.get("approved"))
    n["design"] = "approved"
    n["approved"] = f"{today()} by user"
    n["approved_at"] = now()
    n["approved_hash"] = body_hash(body)
    if re_approval:
        hist(n, "re-approved")
    ambs = led.data.get("ambiguities", [])
    resolved = [x["claim"] for x in ambs if x["resolves_at"] == a.id]
    ambs[:] = [x for x in ambs if x["resolves_at"] != a.id]
    rc = finish(led, f"approved {a.id}" + (f"; resolved ambiguities dropped: {', '.join(resolved)}" if resolved else ""))
    fr = led.frontier()
    new = [it["child"] for it in body if it.get("child") in fr]
    if new:
        print(f"next: `new <dir> {new[0]}`  (frontier: {', '.join(sorted(fr))})")
    elif not fr and not any(x["design"] == "draft" for x in led.nodes.values()):
        print("frontier empty — design complete unless the user reopens something")
    return rc


def flip(led: Ledger, nid: str, design: str, event: str, reason: str, **extra) -> int:
    n = need(led, nid)
    if n is None:
        return 1
    n["design"] = design
    n.update(extra)
    if design != "approved" and n["verification"] == "verified":
        n["verification"] = "stale"
    hist(n, event, reason)
    return finish(led, f"{nid} -> {led.status(nid)}")


def v_reopen(led: Ledger, a) -> int:
    n = led.nodes.get(a.id)
    if n and n.get("body"):  # keep the refinement being replaced as a record
        n["superseded"] = {"date": today(), "reason": a.reason,
                           **{f: n.get(f) for f in ("body", "composition", "decisions", "deferred") if n.get(f)}}
    return flip(led, a.id, "draft", "reopened", a.reason)


def v_stale(led: Ledger, a) -> int:
    return flip(led, a.id, "stale", "stale", a.reason)


def v_supersede(led: Ledger, a) -> int:
    if not led.resolves(a.new_id):
        return fail(f"{a.new_id} does not exist and is not on the frontier")
    return flip(led, a.id, "superseded", "superseded", a.reason, superseded_by=a.new_id)


def v_evidence(led: Ledger, a) -> int:
    n = need(led, a.id)
    if n is None:
        return 1
    n.setdefault("evidence", []).append({"date": today(), "kind": a.kind, "ref": a.ref, "result": a.result, **({"note": a.note} if a.note else {})})
    if a.result == "pass":
        n["verification"] = "verified"
        if n["realization"] == "not-started":
            n["realization"] = "implemented"
    return finish(led, f"{a.id} evidence EV-{len(n['evidence'])} {a.kind} {a.result}; verification {n['verification']}")


def v_entry(led: Ledger, a) -> int:
    f = ENTRY_FILE[a.kind]
    store = led.data.setdefault(f, {})
    heading = a.heading.strip()
    if a.kind == "term":
        if led.entry(heading):
            return fail(f"{heading!r} already exists; `change <dir> \"{heading}\" --definition ... --reason ...`")
        key = heading
        e = {"definition": a.definition.strip(), "confirmed": today()}
        if a.avoid:
            e["avoid"] = [x.strip() for x in a.avoid.split(",") if x.strip()]
        if a.not_:
            e["not"] = [x.strip() for x in a.not_.split(",") if x.strip()]
        if a.example:
            e["example"] = a.example
    else:
        prefix = "CTX-F" if a.kind == "fact" else "CTX-S"
        if is_ctx_id(heading.split(" ", 1)[0]):
            key, heading = heading.split(" ", 1)[0], heading.split(" ", 1)[1].strip() if " " in heading else ""
            if key in store:
                return fail(f"{key} already exists; `change <dir> {key} ...`")
        else:
            key = f"{prefix}{max((int(k[5:]) for k in store), default=0) + 1:02d}"
        e = {"name": heading, "definition": a.definition.strip(), "confirmed": today()}
        if a.kind == "fact":
            e["status"] = "confirmed"
        else:
            for w in ("given", "when", "then", "excludes", "settles"):
                if getattr(a, w):
                    e[w] = getattr(a, w).strip()
    if a.source:
        e["source"] = a.source
    store[key] = e
    return finish(led, f"entry {f}/{key}" + (f" {heading}" if a.kind != "term" else "") + f"; refer to it as `{key}`")


def v_change(led: Ledger, a) -> int:
    hit = led.entry(a.ref)
    if not hit:
        return fail(f"{a.ref!r}: no term / fact / scenario")
    f, key, e = hit
    if a.definition:
        e["definition"] = a.definition.strip()
    if a.status:
        if f != "facts":
            return fail("--status applies to facts only")
        e["status"] = a.status
    if a.rename:
        head = a.rename.strip()
        store = led.data[f]
        if f == "terms":  # terms are keyed by their name; facts and scenarios by their CTX id
            if head in store:
                return fail(f"{head!r} already exists")
            store[head] = store.pop(key)
            for n in led.nodes.values():
                n["depends"] = [head if x == key else x for x in n.get("depends", [])]
            for x in led.data.get("ambiguities", []):
                if x["claim"] == key:
                    x["claim"] = head
            key = head
        else:
            e["name"] = head
    if a.minor:
        return finish(led, f"{f}/{key} reworded (minor, no invalidation)")
    e.setdefault("changed", []).append({"at": now(), "reason": a.reason})
    users = led.used_by().get(key, [])
    return finish(led, f"{f}/{key} changed; dependents to re-check: {', '.join(users) or 'none'} (`stale` or `reopen`+`approve` each approved one)")


def v_meta(led: Ledger, a) -> int:
    if a.field in ("title", "scope"):
        led.data[a.field] = " ".join(a.value).strip()
    elif a.field == "nongoals":
        led.data["nongoals"] = [v.strip() for v in a.value if v.strip()]
    else:
        return fail("meta field must be title | scope | nongoals")
    return finish(led, f"{a.field} set")


def v_ambiguity(led: Ledger, a) -> int:
    ambs = led.data.setdefault("ambiguities", [])
    ambs[:] = [x for x in ambs if x["claim"].lower() != a.claim.strip().lower()]
    if a.drop:
        return finish(led, f"ambiguity {a.claim!r} dropped")
    if not a.conflict or not a.resolves_at:
        return fail('ambiguity <dir> "claim" "conflict" D-NNN   (or --drop)')
    if not is_node_id(a.resolves_at):
        return fail(f"{a.resolves_at!r} is not a D-NNN id")
    ambs.append({"claim": a.claim.strip(), "conflict": a.conflict.strip(), "resolves_at": a.resolves_at})
    return finish(led, f"ambiguity {a.claim!r} -> resolves at {a.resolves_at}")


ADR_STUB = """# {id} — {title}

Kind: adr · Status: proposed · Date: {date}
Constrains: {constrains}
Supersedes: — · Superseded by: —

<1–3 sentences: what's the context, what did we decide, and why.>

## Invariants imposed

- <one line: property every constrained refinement must preserve>
"""


def v_adr(led: Ledger, a) -> int:
    if a.action == "new":
        ids = [w.strip() for w in (a.constrains or "").split(",") if is_node_id(w.strip())]
        if not a.title or not ids:
            return fail('adr <dir> new "Title" --constrains D-NNN[,D-MMM]')
        adr_dir = led.adr_dir() or (led.dir.parents[1] / "adr" if len(led.dir.parents) > 1 else led.dir / "adr")
        adr_dir.mkdir(parents=True, exist_ok=True)
        num = max((int(p.stem[:4]) for p in adr_dir.glob("*.md") if p.stem[:4].isdigit()), default=0) + 1
        slug = "-".join("".join(c.lower() if c.isalnum() else " " for c in a.title).split())[:50]
        path = adr_dir / f"{num:04d}-{slug}.md"
        aid = f"ADR-{num:04d}"
        path.write_text(ADR_STUB.format(id=aid, title=a.title.strip(), date=today(), constrains=", ".join(ids)), encoding="utf-8")
        for nid in ids:
            if nid in led.nodes:
                led.nodes[nid]["adr_pending"] = aid
                if led.nodes[nid]["design"] == "approved":
                    led.nodes[nid]["design"] = "draft"
                    hist(led.nodes[nid], "reopened", f"{aid} proposed")
        return finish(led, f"created {os.path.relpath(path)} ({aid}, proposed). Write the paragraph + invariants by hand, then `sync`; after the user accepts: `adr accept {aid}`")
    if a.action == "accept":
        adr = next((x for x in led.adrs() if x["id"] == a.title), None)
        if not adr:
            return fail(f"{a.title!r}: no such ADR")
        lines = adr["lines"]
        set_header(lines, "Status", "accepted")
        adr["path"].write_text("\n".join(lines) + "\n", encoding="utf-8")
        freed = [nid for nid, n in led.nodes.items() if n.get("adr_pending") == adr["id"]]
        for nid in freed:
            del led.nodes[nid]["adr_pending"]
        return finish(led, f"{adr['id']} accepted; unblocked {', '.join(freed) or 'nothing'}")
    if a.action == "constrains":
        adr = next((x for x in led.adrs() if x["id"] == a.title), None)
        if not adr:
            return fail(f"{a.title!r}: no such ADR")
        ids = [w.strip() for w in (a.constrains or "").split(",") if is_node_id(w.strip())]
        if not ids:
            return fail('adr <dir> constrains ADR-NNNN --constrains D-NNN[,D-MMM]')
        missing = [x for x in ids if not led.resolves(x)]
        if missing:
            return fail(f"{', '.join(missing)}: not a node or frontier id")
        set_header(adr["lines"], "Constrains", ", ".join(ids))
        adr["path"].write_text("\n".join(adr["lines"]) + "\n", encoding="utf-8")
        return finish(led, f"{adr['id']} constrains {', '.join(ids)}")
    if a.action == "supersede":
        by_id = {x["id"]: x for x in led.adrs()}
        old, new = by_id.get(a.title), by_id.get(a.new_adr or "")
        if not old or not new:
            return fail("adr <dir> supersede ADR-OLD ADR-NEW (both must exist)")
        set_header(old["lines"], "Status", "superseded")
        set_header(old["lines"], "Superseded by", new["id"])
        set_header(new["lines"], "Supersedes", old["id"])
        old["path"].write_text("\n".join(old["lines"]) + "\n", encoding="utf-8")
        new["path"].write_text("\n".join(new["lines"]) + "\n", encoding="utf-8")
        return finish(led, f"{old['id']} superseded by {new['id']}")
    return fail("adr <dir> new ... | accept ADR-NNNN | supersede ADR-OLD ADR-NEW | constrains ADR-NNNN --constrains D-NNN")


def v_sync(led: Ledger, a) -> int:
    return finish(led)


def v_check(led: Ledger, a) -> int:
    check(led)
    return report(led)


# ----------------------------------------------------------------------------- main


def log(d: Path, argv: list[str], rc: int) -> None:
    try:
        with (d / LOG).open("a", encoding="utf-8") as f:
            f.write(f"{_dt.datetime.now().isoformat(timespec='seconds')} exit={rc} {' '.join(argv[1:2] + argv[3:])}\n")
    except OSError:
        pass


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(prog="stepwise.py", description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)

    def add(name, *pos, **flags):
        s = sub.add_parser(name)
        s.add_argument("dir")
        for p in pos:
            s.add_argument(p[0], **p[1]) if isinstance(p, tuple) else s.add_argument(p)
        for k, kw in flags.items():
            s.add_argument("--" + k.rstrip("_"), dest=k, **kw)
        return s

    add("frontier"); add("sync"); add("check"); add("show", "id")
    add("new", "id", ("statement", {"nargs": "?"}))
    add("set", "id", "field", ("value", {"nargs": "+"}))
    add("body", "id", file={"default": ""})
    add("answer", "id", "slug", "name")
    add("terminal", "id", "target")
    add("approve", "id")
    add("reopen", "id", "reason"); add("stale", "id", "reason"); add("supersede", "id", "new_id", "reason")
    add("evidence", "id", kind={"required": True}, ref={"required": True}, result={"required": True, "choices": ["pass", "fail"]}, note={"default": ""})
    add("entry", ("kind", {"choices": list(ENTRY_FILE)}), "heading", "definition",
        source={"default": ""}, avoid={"default": ""}, not_={"default": ""}, example={"default": ""},
        given={"default": ""}, when={"default": ""}, then={"default": ""}, excludes={"default": ""}, settles={"default": ""})
    add("change", "ref", definition={"default": ""}, rename={"default": ""}, status={"default": "", "choices": ["", "confirmed", "stale"]}, reason={"required": True}, minor={"action": "store_true"})
    add("meta", "field", ("value", {"nargs": "+"}))
    add("ambiguity", "claim", ("conflict", {"nargs": "?"}), ("resolves_at", {"nargs": "?"}), drop={"action": "store_true"})
    add("adr", ("action", {"choices": ["new", "accept", "supersede", "constrains"]}), ("title", {"nargs": "?"}), ("new_adr", {"nargs": "?"}), constrains={"default": ""})
    a = ap.parse_args(argv[1:])
    d = Path(a.dir).resolve()
    for key in ("id", "new_id"):
        if getattr(a, key, None) is not None and not is_node_id(getattr(a, key)):
            return fail(f"{getattr(a, key)!r} is not a D-NNN id")
    led = Ledger(d)
    if not led.data:
        if a.cmd in ("new", "entry", "meta") :
            led = Ledger.create(d, d.name.replace("-", " ").title())
        else:
            return fail(f"{d / LEDGER} missing; start with `new <dir> D-000 \"outcome <- f(x)\"` or `entry` / `meta`")
    rc = globals()[f"v_{a.cmd}"](led, a)
    if a.cmd not in ("check", "show", "frontier"):
        log(d, argv, rc)
    return rc


if __name__ == "__main__":
    sys.exit(main(sys.argv))
